### ISSUE TITLE
Use short URLs to free space in the terminal

### ISSUE THREAD

**Issue by zoidby** [woefe/ytcc#107]
Hello everyone,

the video URL displayed by setting:
`video_attrs = playlists, title, duration, url`
Currently looks like this:
`https://www.youtube.com/watch?v=oavMtUWDBTM`

Wouldn’t it be a good idea to use youtubes short url style instead?
`https://youtu.be/oavMtUWDBTM`
This is considerably shorter and frees space in the terminal.

In relation i’d like to see the minimum size of the `playlists` column increased. It’s currently only 9 characters before characters are omitted. This can be confusing if you are subscribed to secondary channels with similar names. Ideally this could be adjusted via the config file but for me it would be enough to add the 15 free characters from the shorter URLs so that the new minimum would be 24 characters.

**Comment by woefe** [comment]
I agree that the narrow columns on small screens are missing information. I've implemented a "plain" output format which is then used in the preview window of `ytccf.sh` (see https://github.com/woefe/ytcc/pull/108 ). Cut-off values can be shown in the preview window of `ytccf.sh`

**Comment by woefe** [comment]
I'm not to keen on messing with the table / column width calculations neither replacing the URLs with shortened ones.
