### ISSUE TITLE
Show which subcription an update error belongs to

### ISSUE THREAD

**Issue by wavexx** [woefe/ytcc#110]
**Describe the bug**
I sometimes get errors of the form:

```
WARNING: Failed to get a video. Error was: 'ERROR: [youtube] <ID>: <error>'
```

However I have no idea from which subscription this video id/error is coming from.
Since I see no title either, it's hard to tell if I should care.

**To Reproduce**
Pick any subscription with live events to have a video that generates an error.
One random example: https://www.youtube.com/channel/UCZFipeZtQM5CKUjx6grh54g

**Expected behavior**
Showing an error of the form:

```
WARNING: <subscription name>: <rest of the error>
```

would be very helpful. If the expected title of the video is available, showing this after the video ID would also be nice to have.

**Environment, configuration and version information**
```
ytcc bug-report
---ytcc version---
2.5.4

---youtube-dl version---
youtube-dl not found

---yt-dlp version---
2022.08.19

---Click version---
8.0.3

---SQLite version---
SQLite system library version: 3.39.2
Python module version: 2.6.0

---python version---
3.10.6 (main, Aug 10 2022, 11:19:32) [GCC 12.1.0]
```

**Comment by woefe** [comment]
Fixed in be9a217
