### ISSUE TITLE
broken YTCC after Archlinux update

### ISSUE THREAD

**Issue by Gohub007** [woefe/ytcc#116]
after a major update on Archlinux we have a broken YTCC command. We downgraded the corresponding dependencies of YTCC but python error remains.

**To Reproduce**
Steps to reproduce the behavior: ytcc update
               
**Expected behavior**

**Environment, configuration and version information**
Archlinux Gnome 43.5 Wayland
YTCC Version                  : 2.6.1-1

Add the output of `ytcc bug-report` here

Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ytcc", line 33, in <module>
    sys.exit(load_entry_point('ytcc==2.6.1', 'console_scripts', 'ytcc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/ytcc", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for ytcc
```

**Debug log (optional)**
Enable the debug logging and run buggy command again. Note, that this can print sensitive information!
``` 
ytcc --loglevel debug <your command here>
```

**Additional context**
Add any other context about the problem here.

**Comment by Gohub007** [comment]
we installed the Archlinux **ytcc-git   r447.8893bc9-1** the problem is solved

**Comment by Gohub007** [comment]
we installed the Archlinux **ytcc-git   r447.8893bc9-1** the problem is solved

**Comment by Gohub007** [comment]
change from aur/ytcc to aur/ytcc-git solved the issue

**Comment by woefe** [comment]
Reinstalling the stable package should also have solved the issue. This is normal whenever there is a bigger Python update in Arch. Thanks for bringing this. I was late on my Arch updates this time and did not notice.  

Bumped the stable package pkgrel. You should be able to install the non git package again.
