### ISSUE TITLE
Categorization of video subscriptions

### ISSUE THREAD

**Issue by ghost** [woefe/ytcc#23]
Sometimes I might want to watch a certain genre of YouTube subscriptions, like music, tech, news, or podcasts. It would be nice if we could categorize our subscription feeds so we could watch only what we're in the mood for.

**Comment by MicrosoftTakeover** [comment]
Just expanding on how this could be done:
* An optional feature of the add argument, for example: `ytcc -a NAME URL TAG`
* Subscriptions with no tags could be tagged as "undefined".
* A new column in the listing called tag.
* A new argument called --tag, such as `ytcc--tag tech`

I know this is somewhat already covered by the filter feature, but I think this could be expanded further by the system I have described above.

**Comment by woefe** [comment]
Cool idea! I added it to the new v2 milestone, because this change is not backwards compatible with existing installations (all existing channels would have an empty tag, and the `-a` flag will be changed)

**Comment by MicrosoftTakeover** [comment]
I don't think this has to be a breaking change, set all existing channels to "undefined" until the user wants to add a tag to them. Make the TAG argument in the `-a` flag optional.

**Comment by woefe** [comment]
Tagging, which solves this use-case, is now available on the v2 branch. v2 is still very unstable. I'll update the README as soon as I have a beta version ready
