### ISSUE TITLE
ytcc video resolution settings funtioning inconsistantly

### ISSUE THREAD

**Issue by pghpete** [woefe/ytcc#24]
First, thank you for this awesome tool and great work on it! I truly appreciate it.  If I can help debugging this issue or testing changes please let me know. (I'd be happy to do so)

The issue I have is that I would like ytcc to only pull videos that are 1920 x 1080 or higher in resolution and it sometimes works, sometimes pulls 640x480 or lower.

I have had my ytcc.conf file (located in /home/user/.config/ytcc.conf) set to, 1080, 1920, etc but cannot get this to function correctly or consistently. 

From ytcc.conf file...
`[youtube-dl]`
`format = mkv/mp4/bestvideo[height>=1920]+bestaudio/best`

Attached is a bug-report-info file.

[ytcc-bug-report-info.txt](https://github.com/woefe/ytcc/files/3932867/ytcc-bug-report-info.txt)

I would also like to know if you would be interested in a proper man page for this utility.  I would gladly assist in its creation and submission to this project.

Thank you.
Pete

**Comment by woefe** [comment]
I think the problem is that you have mkv, mp4 and best without the height qualifier. Your format selector will always go for mkv or mp4, if available, regardless of the resolution.

Try for example: `bestvideo[height>=1080]+bestaudio/best[height>=1080]`.

**Comment by pghpete** [comment]
The issue is that I am using this to populate minidlna to steam content and I cannot use webm/dash, and other various video/audio encoded videos.  Is there not a way to both force a proper extension/encoding and screen resolution?

Using youtube-dl you can do something like this, which will get you the best resolution then merge output to mkv. 

`youtube-dl -i -o "%(uploader)s.%(title)s.%(ext)s" --skip-unavailable-fragments --merge-output-format "mkv"`

I will try what you recommended though and see if I get dnla stream-able videos.

Thanks again for your assistance.

**Comment by pghpete** [comment]
I am still unable to get it to only get 1920x1080 or better using...

[youtube-dl]
format = mkv/mp4/bestvideo[height>=1080]+bestaudio/best[height>=1080]

**Comment by woefe** [comment]
I added the merge_output_format option in 6d9ad60, because it seemed to fix your problem when using youtube-dl directly. Try the latest commit on the master branch and set the following config. It will get the bestvideo+bestaudio and merge them to a mkv container or use the best single file format available.

```
[youtube-dl]
format = bestvideo+bestaudio/best
mergeoutputformat = mkv
```

**Comment by pghpete** [comment]
Giving it a go now.  Thank you!  I will report back when I see some additional videos yanked.

**Comment by pghpete** [comment]
Works perfectly! Thank you very much for your work on this project and for your help here. I greatly appreciate it.

**Comment by woefe** [comment]
Thanks!

**Comment by pghpete** [comment]
Woefe, did this merge_output option go away in the latest revision? Was the change made on the main branch? Seems all of a sudden my system is ignoring it and dumping webm files instead.

**Comment by pghpete** [comment]
ignore that  pghpete dude. he's mistaken. dope. :)

new system lacked ffmpeg for some reason so it couldn't do the merge post download.
