### ISSUE TITLE
Restrict YtCC to playlist within channel?

### ISSUE THREAD

**Issue by BronnEdward** [woefe/ytcc#27]
It appears to me that ytcc operates only on a Youtube 'Channel' basis (I may be wrong)..  My question, Is there a way to limit ytcc results to a single 'Playlist' within a Channel?

For example, say Youtube channel 'X' posts many videos into numerous different playlists.  Is there a way to limit ytcc to downloading only videos from within a single playlist rather than from all videos on the 'Videos' page of the given channel?

I have been able to do the same from CLI with youtube-dl, but seems to not be possible currently with ytcc. I would prefer to use ytcc as it seems much more efficient on network calls.  Apologies for the naive question.   Thanks!

**Comment by woefe** [comment]
This will come in a v2. I have been working on a new version of ytcc, which is based on the youtube-dl playlist features. It will be taking advantage of some youtube-dl internals to provide more efficient network calls than using youtube-dl directly. It will also solve some of the other open issues.

I hope to release an alpha version soon.

**Comment by BronnEdward** [comment]
Fantastic!..  Thank you.  ..regardless of current limitations, thank you for what you have already created! It has improved my quality of life. :)
