### ISSUE TITLE
ytcc -a .... is not a valid YouTube URL

### ISSUE THREAD

**Issue by Gohub007** [woefe/ytcc#30]
adding any channel does not work any longer: 
`ytcc -a "Jupiter Broadcasting" https://www.youtube.com/user/jupiterbroadcasting is not a valid YouTube URL`

ytcc --bug-report-info:

`---ytcc version---
1.8.3

---youtube-dl version---
2020.06.16.1

---SQLAlchemy version---
1.3.18

---feedparser version---
5.2.1

---lxml version---
4.5.2

---python version---
3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]

---mpv version---
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.3

---config dump---
[YTCC]
dbpath = ~/.local/share/ytcc/ytcc.db
downloaddir = ~/Downloads
mpvflags = --really-quiet --ytdl --ytdl-format=bestvideo[height<=?720]+bestaudio/best
alphabet = sdfervghnuiojkl
orderby = channel, date
defaultaction = play_video

[color]
promptdownloadaudio = 2
promptdownloadvideo = 4
promptplayaudio = 2
promptplayvideo = 4
promptmarkwatched = 1
tablealternatebackground = 245

[youtube-dl]
format = bestvideo[height<=?1080]+bestaudio/best
outputtemplate = %(title)s.%(ext)s
loglevel = normal
ratelimit = 0
retries = 0
subtitles = off
thumbnail = on
skiplivestream = yes
mergeoutputformat = mkv

[TableFormat]
id = on
date = off
channel = on
title = on
url = off
watched = off`

**Comment by woefe** [comment]
Fixed in #28
