### ISSUE TITLE
Filter by channel in the TUI

### ISSUE THREAD

**Issue by EmRowlands** [woefe/ytcc#48]
**Is your feature request related to a problem? Please describe.**
In v1, there was the handy `-f` switch that allowed for filtering the channels in the TUI.

**Describe the solution you'd like**
It would be good if this, or something similar were to be reimplemented in v2. It would also be good to be able to filter by tag.

**Describe alternatives you've considered**
It's possible that it could instead be applied *within* the TUI, but this doesn't match the v1 feature. This would be a nice addition, but not a replacement in my opinion.

**Additional context**
My use case for this is that I have a couple of different aliases (for v1) that look like this: `ytcc -f <lots of channels>`.

**Comment by woefe** [comment]
Actually, I had plans to remove the TUI altogether in favor of a fzf script. But I decided to keep it to have an easier setup on platforms that cannot run the fzf script (Windows). 

Can you try https://github.com/woefe/ytcc/blob/master/scripts/ytccf.sh and tell me if that fixes the issue? And also tell me if it's fast enough. I've improved the startup time of ytcc a bit to allow quicker previews in fzf. You can search for multiple channels with `|`: `channel1 | channel2`. And you can also filter from the command line.

**Comment by EmRowlands** [comment]
The fzf script *does* work, but having the `-f` switch can provide utility outside of a TUI.

I decided to take a look at implementing this myself, and it was a lot easier than I expected due to your previous abstractions with the list and ls commands. I have created the pull request as #49.

**Comment by woefe** [comment]
Fixed in e220b6f
