### ISSUE TITLE
[Enhancement] Allow choosing audio only on a per-video basis.

### ISSUE THREAD

**Issue by HeatedTea** [woefe/ytcc#5]
I'm aware I can switch ytcc to audio only using -x, but I'd like if I could choose individually for each video.

So instead of:
`Play video "Level1 News December 12 2017: Yo Dawg, I Heard you Like A.I." by "Level1Techs?"
[y(es)/n(o)/m(ark)/q(uit)/h(elp)] (Default: y): `

It would be:
`Play video "Level1 News December 12 2017: Yo Dawg, I Heard you Like A.I." by "Level1Techs?"
[y(es)/n(o)/m(ark)/a(udio)/q(uit)/h(elp)] (Default: y): `

This way you could simply press 'a' for audio only.

_Also I just noticed that the question mark at the end is inside the quotation marks which makes it look like it's part of the channel name._

Thanks woefe for your great work on ytcc, I use it every day.

**Comment by woefe** [comment]
It is actually possible to play only the audio track by typing 'a' in the prompt. But this is not documented anywhere. The help text says `play-audio  play only the audio track of the video`, but there is no indication that it also works by just typing `a`. I'll try to improve the help text and maybe add the `a(udio)` option to the prompt.

**Comment by HeatedTea** [comment]
Oh wow, this feature has been hiding under my nose this whole time if only I had just tried it.

**Comment by woefe** [comment]
The `help` text shows the shortcut commands now. Also, there are no redundant commands any more (e.g. `play-video` and `yes` did the same thing). And I added the `audio` option to the prompt.
