### ISSUE TITLE
[V2] Ability to sort video_attrs

### ISSUE THREAD

**Issue by zoidby** [woefe/ytcc#58]
It would be nice if the order of columns in V2 would reflect the order of this config option like in the old version:

Default:
`video_attrs = id, title, publish_date, duration, playlists`

Alternative order that i like:
`video_attrs = playlists, title, duration, publish_date`

**Comment by woefe** [comment]
I like that Idea! Same should also be implemented for `--attributes` options.

**Comment by woefe** [comment]
I've implemented this in PR #61. Can you try it out and let me know if it's working for you?

**Comment by zoidby** [comment]
Yes, that works.

Thanks for implementing it!
