### ISSUE TITLE
[V2] Don’t ignore age restricted videos

### ISSUE THREAD

**Issue by zoidby** [woefe/ytcc#59]
Currently ytcc/V2 ignores videos "due to age limit".

As far as i know this was implemented because youtube changed the api and youtube-dl couldn’t download these videos anymore. But, it seems to work again! I checked some of the videos ytcc/V2 ignored and was able to download them with youtube-dl or play them with mpv.

So could you include these videos again?

In case youtube restricts these again, youtube-dl also has options to give your login credentials. An alternative option would be to launch age restricted videos in a browser instead of mpv.

**Comment by woefe** [comment]
Have you tried adjusting the `age_limit` option in your config file? By default, ytcc basically sets `--age-limit 0`.

**Comment by zoidby** [comment]
Oh, i misunderstood this option then. I thought that was to filter older videos.

So `age_limit = 0` should display age restricted videos right? As this seems to be the default option, i wonder why i saw all these `WARNING: Ignoring video 'XYZ' due to age limit` when importing my subscriptions.

**Comment by woefe** [comment]
No, it's the other way around. `age_limit = 0` does not show any age restricted videos. It's a bit confusing. It sets youtube-dl's age limit option. From youtube-dl(1):
```
--age-limit YEARS
        Download only videos suitable for the given age
```

**Comment by zoidby** [comment]
Ok, i set it to 9000 then and see if it works in the future.

Because as it seems, already ignored videos didn't get added after changing the setting and updating the database.

Thank you, you can close this then.

**Comment by woefe** [comment]
> Ok, i set it to 9000 then and see if it works in the future.

Correct. That should work.

> as it seems, already ignored videos didn't get added after changing the setting and updating the database.

By default, ytcc ignores videos that failed to update 5 times. You can set this threshold with the `--max-fail` option. You can try to import the failed videos again (after setting the new age limit) with following command:
```
ytcc update  --max-fail  100
```

**Comment by zoidby** [comment]
Oh nice, thank you!
