### ISSUE TITLE
Ctrl+d has to be hit twice to exit if switched to a different view mode

### ISSUE THREAD

**Issue by zoidby** [woefe/ytcc#63]
If you switch to a different view mode in the tui, you have to hit Ctrl+d twice to exit.

I don’t know python, but in bash you would catch the ^D and execute an exit function.

**Comment by woefe** [comment]
I know. This has been around since v1. I think that some escape sequences are not fully consumed when pressing the F-keys. I'll try to debug it again.

**Comment by zoidby** [comment]
Yep, i was holding back reporting it for v1 since you were already working on v2.

**Comment by woefe** [comment]
Fixed in 62310b9.
