### ISSUE TITLE
Other "Youtube" Providers

### ISSUE THREAD

**Issue by nobicycle** [woefe/ytcc#7]
I was wondering if you are considering supporting other video provider services, especially those who are not Orwellian like youtube. What I consider as innocent videos are getting pulled from Youtube even  in the midst of being downloaded by ytcc.  This has gone too far. If the excellent ytcc only supports youtube then 
regretfully from now on I will not use it.

Bitchute would be an example of a popular alternative.

Best wishes

**Comment by woefe** [comment]
It could be done, but there are restrictions for other providers. In particular:

* youtube-dl needs to support it
* The platform must have channels (like YouTube channels)
* RSS feed of latest videos per channel

I have quickly checked Bitchute and DTube. Bitchute is not supported by youtube-dl and DTube does not have RSS feeds.

**Comment by marius851000** [comment]
I'm actually working on this, using the playlist option of youtube-dl.

**Comment by woefe** [comment]
I have checked Bitchute again and it is working properly with youtube-dl now and also has RSS feeds. The same is true for Peertube. Support for both of them is coming as soon as I find some time to implement it.

**Comment by woefe** [comment]
I realized that with the current code base this is more effort than anticipated. And it will need a database schema upgrade. I will add this issue to the v2 milestone.

For now, if you want to use a provider other than YouTube and want to put in some more effort, you could probably set up something with [newsboat](https://github.com/newsboat/newsboat).

**Comment by woefe** [comment]
Has been added on the v2 branch. v2 is still very unstable. I'll update the README as soon as I have a beta version ready
