### ISSUE TITLE
New channel url doesn’t get parsed

### ISSUE THREAD

**Issue by zoidby** [woefe/ytcc#73]
Previously, channel URLs were in the form of

`https://www.youtube.com/channel/...`

That seems to have been changed to:

`https://www.youtube.com/c/...`

Adding a channel with the new URL doesn’t resolve the playlist.

**Comment by woefe** [comment]
Something in youtube-dl's YouTube extractor changed. Channel URLs do not resolve to playlists anymore. As a workaround you can use `youtube.com/.../videos`

**Comment by woefe** [comment]
ytcc now performs stricter checks when subscribing. You cannot subscribe to channel URLs directly anymore. The new youtube-dl extractor for YouTube channels basically extracts a playlist of playlists. Ytcc cannot handle nested playlists.

Closed with 1b1f293.
