### ISSUE TITLE
ytcc broken

### ISSUE THREAD

**Issue by Gohub007** [woefe/ytcc#77]
**Describe the bug**
Archlinux updated today some python library, since then ytcc is broken

**To Reproduce**
any ytcc command fails with:

Traceback (most recent call last):
  File "/usr/bin/ytcc", line 33, in <module>
    sys.exit(load_entry_point('ytcc==2.0.1', 'console_scripts', 'ytcc')())
  File "/usr/bin/ytcc", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ytcc

**Expected behavior**

upgraded python-click (7.1.2-1 -> 7.1.2-3)
upgraded python-setuptools (1:50.3.2-1 -> 1:50.3.2-4)
upgraded python-wcwidth (0.2.5-1 -> 0.2.5-3)

downgrading the updated python library could not solve the issue:
downgraded python-wcwidth (0.2.5-3 -> 0.2.5-1)
downgraded python-click (7.1.2-3 -> 7.1.2-1)
downgraded python-setuptools (1:50.3.2-4 -> 1:50.3.2-1)

**Environment, configuration and version information**

LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

Add the output of `ytcc bug-report` here
```
ytcc bug-report
Traceback (most recent call last):
  File "/usr/bin/ytcc", line 33, in <module>
    sys.exit(load_entry_point('ytcc==2.0.1', 'console_scripts', 'ytcc')())
  File "/usr/bin/ytcc", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ytcc

**Comment by Glandos** [comment]
This is clearly not a bug from ytcc, but from your distribution or environment. It seems that the main script `/usr/bin/ytcc` is still installed, but the whole package (usually in `/usr/lib/python3.9/site-packages/ytcc` disappeared. You should try to use your package manager to check if files are missing, or try to reinstall ytcc.

**Comment by Gohub007** [comment]
reinstall ytcc solved the issue, thank you
