### ISSUE TITLE
TUI shortcut for unmarking the last video played

### ISSUE THREAD

**Issue by EmRowlands** [woefe/ytcc#89]
**Is your feature request related to a problem? Please describe.**
When I accidentally quit `mpv` before I want to, I have to quit the TUI, find the video ID, and manually unmark it. This is really annoying.

**Describe the solution you'd like**
A keybind in the TUI to unmark the last video watched would be the best in my opinion.

**Describe alternatives you've considered**
A keybind for simply replaying the last video watched would also work. I prefer the unmark option, but I think I think it would only really be a matter of preference.

**Comment by woefe** [comment]
Implemented in a3bb3a1
