### ISSUE TITLE
Truncate long titles

### ISSUE THREAD

**Issue by zoidby** [woefe/ytcc#91]
Videos sometimes come with very long titles so that the tui-table exceeds the width of the terminal. This in turn leads to line breaks which make the interface messy. Please see this screenshot for example: 
![screenshot--2021-05-30--17-35-49](https://user-images.githubusercontent.com/44140842/120110424-ad6b0480-c16d-11eb-909b-9f227f79f66f.png)

The ideal solution would be to have a line break only in the single cell, that exceeds the limit.

But i guess that could be to much to implement. Truncating the title (and maybe putting … to indicate it) so that the whole row will never be longer than the term width would be sufficient as well.

**Comment by woefe** [comment]
Yes, I agree. I thought about multiline tables a while back, but I couldn't find an easy way to do it.

Instead, I have now implemented the truncating of long lines. It still needs some work. See #92
