### ISSUE TITLE
filtering ?

### ISSUE THREAD

**Issue by humanitiesNerd** [woefe/ytcc#93]
It's june 2021 and I just installed version 2.0 with pipx

I subscribed to a bunch of channels and I'd like to be able to filter the list of videos

For example, I'd like to see the videos from one channel only

I remember this was possible in version 1.x

How do I do that now ?

Thanks

**Comment by EmRowlands** [comment]
You can use a bunch of different filtering arguments with the list, tui and ls subcommands. Here is an extract from the man page:

```
       -a, --attributes COMMA_SEPARATED_VALUES Attributes of videos to be included in the output. Some of [id, url, title, description, publish_date, watched, duration, extractor_hash, playlists].
       -c, --tags COMMA_SEPARATED_VALUES Listed videos must be tagged with one of the given tags.
       -s, --since [%Y-%m-%d] Listed videos must be published after the given date.
       -t, --till [%Y-%m-%d] Listed videos must be published before the given date.
       -p, --playlists COMMA_SEPARATED_VALUES Listed videos must be in on of the given playlists.
       -i, --ids COMMA_SEPARATED_VALUES Listed videos must have the given IDs.
       -w, --watched Only watched videos are listed.
       -u, --unwatched Only unwatched videos are listed.
       -o, --order-by <CHOICE CHOICE>...  Set the column and direction to sort listed videos.
```

**Comment by humanitiesNerd** [comment]
ah I haven't found the man page, sorry

May I ask you where is it ?

**Comment by EmRowlands** [comment]
`man 1 ytcc`

**Comment by humanitiesNerd** [comment]
ehm...

no

I installed with pipx (in order to have a recent version) and man isn't available

I didn't even find it in this repo ¯\_(ツ)_/¯

**Comment by humanitiesNerd** [comment]
ah it's

https://github.com/woefe/ytcc/blob/master/doc/ytcc.1

sorry
