### ISSUE TITLE
youtube subscription export doesn't work anymore

### ISSUE THREAD

**Issue by FredjeVa** [woefe/ytcc#94]
https://www.youtube.com/subscription_manager doesn't offer export option anymore,
yopml file from google takeout should be made compatible or a script to convert them could be provided, as I have no access to an original subscription export I wasn't able to create one

**Comment by TrevCan** [comment]
Hey, I just found out that you can access your youtube subscriptions through here: https://takeout.google.com . 

**Unfortunately, they are accessible only in a JSON format**

1. After accessing the website, click on **Create new export** and **Deselect all**. 
2. Scroll down to 'Youtube and Youtube Music. 
3. Then click on 'All Youtube Data Included' and again, 
4. click on 'deselect all' and check only the *subscriptions* entry. 
5. After that, click on next, 
6. click on *Create Export*
7. decompress the downloaded `.zip` file, you should end up with a json file called `subscriptions.json`

After that, you should be able to use a JSON to OPML parser, such as this one: https://iuriioapps.com/tools/youtube-subs-opml/ which sort of worked, after downloading the OPML file like half of my subscriptions weren't there. Nevertheless, I'm working on a patch that can parse this json file and feed it into `ytcc`

**Comment by TrevCan** [comment]
Hello @FredjeVa , I've found a way to download your YT subscriptions using Google Takeout, more info in [this readme](https://github.com/TrevCan/ytcc/blob/master/doc/yt_export_subs.md).

I have fixed this issue! See PR #95 or run the code from [my branch](https://github.com/TrevCan/ytcchttps://github.com/TrevCan/ytcc) and let me know if it works! I've already tested this with my subscriptions and it definitely works!

**Comment by woefe** [comment]
The takeout does not give a JSON any more, AFAIK. It only produces a CSV file.

**Comment by woefe** [comment]
The CSV importer is implemented in 10b6f55
